import { useEffect, useState } from 'react'
import { Bot } from 'lucide-react'
import { useApp } from '../hooks/AppContext'
import ConnectionStatus from '../components/ConnectionStatus'
import AIChat from '../components/AIChat'
import { getAIStatus } from '../services/hybridAIService'

export default function AIAssistant() {
  const { online } = useApp()
  const [aiStatus, setAiStatus] = useState('checking')

  useEffect(() => {
    let cancelled = false
    getAIStatus().then((status) => {
      if (!cancelled) setAiStatus(status)
    })
    return () => {
      cancelled = true
    }
  }, [online])

  const footerText = !online
    ? 'Offline mode uses the local rule engine only. Cloud AI will resume automatically when you\u2019re back online.'
    : aiStatus === 'live'
      ? 'Answers are generated by Claude AI and grounded in the SmartDesk knowledge base. Double-check anything risky before applying it.'
      : aiStatus === 'mock'
        ? 'The backend is running but no AI key is set, so replies are demo answers. Add ANTHROPIC_API_KEY to backend/.env for live AI.'
        : aiStatus === 'unreachable'
          ? 'The AI backend isn\u2019t reachable, so SmartDesk is answering from its local knowledge base. Start the backend for live AI.'
          : 'Checking AI connection\u2026'

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="flex items-start gap-3">
        <div className="w-11 h-11 rounded-lg border border-cyan/30 bg-cyan/10 flex items-center justify-center text-cyan glow-ring">
          <Bot size={20} />
        </div>
        <div>
          <h2 className="font-display text-2xl font-semibold text-text">SmartDesk AI Assistant</h2>
          <p className="text-text-dim text-sm mt-1">Ask a question in plain language and get a step-by-step diagnosis.</p>
        </div>
      </div>

      <ConnectionStatus online={online} />

      <AIChat />

      <p className="text-xs text-text-faint text-center">{footerText}</p>
    </div>
  )
}
